### ISSUE TITLE
`ZmqConnection.close` should be a no-op

### ISSUE THREAD

**Issue by shs96c** [zeromq/jeromq-jms#12]
`javax.jms.Connection` is `AutoCloseable`, so expected usage is in a try-with-resources block. This automatically calls `close` when leaving the block. The current implementation of `ZmqConnection.close` throws an `UnsupportedOperationException`. Making this a no-op (and potentially logging the problem?) would allow the expected JMS usage to work.

**Comment by mjeremym** [comment]
Fixed in release 3.0
