### ISSUE TITLE
Release of this project?

### ISSUE THREAD

**Issue by scoheb** [zeromq/jeromq-jms#2]
Hi,

I just want to know if you intend on making a release of this product on Maven Central?

Thanks

Scott

**Comment by mjeremym** [comment]
Sounds great. Fine by me

Jeremy

**Comment by scoheb** [comment]
what is your time frame for creating the release?

I would like to include your package with my Jenkins plugin here:
https://github.com/jenkinsci/jms-messaging-plugin

Currently, I am cheating by using a local lib file as my dependency.

Thanks!

SH

**Comment by mjeremym** [comment]
Sorry should have read you email properly.

Forgot it was not and actual real lease on maven central and still a snapshot. Been a while since I looked into it. Better refresh myself in what was required. Should be just released. 

Jeremy

**Comment by mjeremym** [comment]
I have managed to release

/org/zeromq/jeromq-jms/1.0-RELEASE/jeromq-jms-1.0-RELEASE.jar

Hopefully, all the steps have been done now to push it to maven central.

regards
Jeremy

**Comment by mjeremym** [comment]
I can see the JAR within maven repositories

https://mvnrepository.com/artifact/org.zeromq/jeromq-jms/1.0-RELEASE

**Comment by scoheb** [comment]
Thanks alot!

Any future plans for this? new features etc?

**Comment by mjeremym** [comment]
I have release 1.1 with your bug fix and one I found.

I was trying to write a message store to enable optional BCP functionality. Put the hocks in, and the first cut of file based journalling, but not sure it is working correctly yet.
