### ISSUE TITLE
Extended is not working

### ISSUE THREAD

**Issue by Zurvarian** [zeromq/jeromq-jms#7]
Hello, 

I've been testing this library and found that I cannot make "extend=<parent>" in the query params to work.
I've defined a parent topic and pass it in the ZmqConnectionFactory destinations parameter, then I've tried to create the topic using the ZmqSession obteined from the ZmqConnection created by the mentioned ZmqConnectionFactory, but I get an error saying "Unable to resolve 'socket.addr' or 'gateway.addr'" for my queue URI.

Additionally to the error previously mentioned, I've tried to download the project and see how ZmqExtendedURI is used, but I couldn't find any reference to that class being used, except for the corresponding UnitTest class.

Best regards,

**Comment by mjeremym** [comment]
Fixed in release 3.0
